# Generated by Django 4.0.5 on 2022-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=20)),
                ('active_requests', models.IntegerField()),
            ],
        ),
    ]
